export const ADD_TODO = "ADD_TODO";
export const EDIT_TODO = "EDIT_TODO";
export const DELETE_TODO = "DELETE_TODO";
export const SORT_TODO_BY_PRIORITY = "SORT_TODO_BY_PRIORITY";
export const SORT_TODO_BY_TIME = "SORT_TODO_BY_TIME";
export const SORT_TODO_BY_STATUS = "SORT_TODO_BY_STATUS";
export const FILTER_BY_STATUS = "FILTER_BY_STATUS";